before_install:
- sudo apt-get update 

install:
- wget -O opa https://github.com/open-policy-agent/opa/releases/download/v0.9.2/opa_linux_amd64
- chmod 755 ./opa

script:
- ./opa test --coverage -v bpm
- tar --exclude='*test.rego' -zcvf bpm.tar.gz bpm

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: bpm.tar.gz
  skip_cleanup: true
  on:
    tags: true